### ISSUE TITLE
Rework the search feature

### ISSUE THREAD

**Issue by kobayashi90** [victoralvesf/aonsoku#65]
Currently the Search only shows 5 albums and doesnt give you an way to show all entries like other webuis do this..
(Navidome does this also, Feishin also)

Its pretty annoying to always type the full album name in just to find something with the current version of the search.
sorry for reporting so many smaller findings but its really annoying.. dont get me wrong i love this just has a lot of smaller issues.
let me know if you need more info.
thx

**Comment by victoralvesf** [comment]
Thanks for your suggestion! There's no problem at all—keep reporting these small improvements; that's how the app will keep getting better and better.

As of now, I can only imagine a `See more` link that redirects to the albums page with all the results. However, I'm open to suggestions, so feel free to share your thoughts!

**Comment by kobayashi90** [comment]
Yeah "See More" seems like an great idea.

**Comment by victoralvesf** [comment]
## Task
Add a "See More" link for albums and songs in the command dialog.

### Details
To address space constraints in the command dialog, a "See More" link should be added for both albums and songs.

### Actions
- [ ] When the user clicks the "See More" link under albums, they should be redirected to the albums page displaying the complete list of results.
- [ ] When the user clicks the "See More" link under songs, they should be redirected to the songs page with all results shown.
- [ ] Move the artist results to the third position so albums and songs appear first.

### Examples

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/02c334eb-96a5-4504-bbae-abe82c65d359)

</p>
</details> 

## Notes

> A similar feature could potentially be implemented for artists. However, this would require restructuring the current layout of the artists page.

**Comment by Borber** [comment]
This feature is very much needed, and I am eagerly awaiting a version to be released. If the experience exceeds Feishin, I will also invest time to contribute to the project

**Comment by victoralvesf** [comment]
Now available in version 0.5.0.
